### ISSUE TITLE
store_entity_semantic_embeddings removed in latest graphrag package

### ISSUE THREAD

**Issue by BobbyAxelrods** [noworneverev/graphrag-api#3]
Hi, 

As the graphrag updated , by any chance this repo will be updated? The store_entity_semantic_embeddings function removed from dfs.py and this repo no longer working with latest version of graphrag. 

Thanks

**Comment by noworneverev** [comment]
> Hi,
> 
> As the graphrag updated , by any chance this repo will be updated? The store_entity_semantic_embeddings function removed from dfs.py and this repo no longer working with latest version of graphrag.
> 
> Thanks

Yes, I have drafted the changes to work with the latest major version (v1.0.0) of GraphRAG. You can check the branch [feature/graphrag-v1.0.0](https://github.com/noworneverev/graphrag-api/tree/feature/graphrag-v1.0.0). After further testing, I'll merge it into the main branch. Thank you.

**Comment by noworneverev** [comment]
The changes have been merged. Thank you.
